/**
 * Field Catalog Configuration
 *
 * Comprehensive catalog of database fields with their natural language synonyms
 * and example queries. Used by Phase 1 (Intent & Field Identification) to help
 * the LLM understand which fields users are requesting.
 *
 * Structure:
 * - Table name → Field name → Array of [synonyms, natural language query examples]
 *
 * Database assignment:
 * - Main DB: Client (users table not included as it's managed separately)
 * - Client DB: Project, ProjectMember, TimeEntry, Task, Conversation, Message, ResponseRating, Invoice, InvoiceItem, InvoicePayment
 */

import type { FieldCatalog } from '../types/field-catalog.types';

export const FIELD_CATALOG: FieldCatalog = {
  Client: {
    id: [
      'client id',
      'customer id',
      'account id',
      'What is the id of the client?',
      'Show me client details by id',
      'Find client by id',
    ],
    name: [
      'client name',
      'customer',
      'company',
      'business',
      'Show all clients named X',
      'Search for client by name',
      'Find company called Y',
    ],
    slug: [
      'client slug',
      'short name',
      'url id',
      "What's the client slug?",
      'Find client with this url id',
    ],
    isActive: [
      'active',
      'enabled',
      'current',
      'status',
      'Which clients are active?',
      'Show all inactive customers',
      'List current clients',
    ],
    hourlyRate: [
      'rate',
      'hourly rate',
      'billing rate',
      'cost/hour',
      "What is the client's hourly rate?",
      'How much do we charge this client per hour?',
    ],
    discountPercentage: [
      'discount',
      'client discount',
      'discount rate',
      'percent off',
      'Does this client get a discount?',
      'What percent discount does the client have?',
    ],
    email: [
      'email',
      'client email',
      'contact email',
      "What's the client's email address?",
      'Find clients without an email',
    ],
    phone: [
      'phone',
      'telephone',
      'contact number',
      "What is the client's phone number?",
      'Show me customers by phone',
    ],
    website: [
      'website',
      'url',
      'homepage',
      "What is the client's website?",
      'List customer websites',
    ],
    contactPerson: [
      'contact',
      'contact person',
      'main contact',
      "Who is the client's contact person?",
      'Show me client contacts',
    ],
    billingAddressLine1: [
      'address',
      'billing address',
      'street address line 1',
      "What's the client's billing address?",
      'Find clients in a certain city',
    ],
    billingAddressLine2: [
      'address 2',
      'apt or suite',
      'street address line 2',
      "What's the full billing address for this client?",
    ],
    billingCity: [
      'city',
      'billing city',
      'location city',
      'Show me clients in Minneapolis',
      'Find clients by billing city',
    ],
    billingState: [
      'state',
      'province',
      'region',
      'List clients by state',
      'What state is a customer billed in?',
    ],
    billingPostalCode: [
      'zip',
      'postal code',
      'zip code',
      'Find clients by postal code',
      'Show clients in ZIP 55416',
    ],
    billingCountry: [
      'country',
      'nation',
      'What country is the client in?',
      'Show clients by billing country',
    ],
    invoicePrefix: [
      'invoice prefix',
      'invoice code',
      "What prefix is used for this client's invoices?",
      'Show invoice code format',
    ],
    invoiceNextNumber: [
      'next invoice number',
      'last invoice number',
      'invoice counter',
      "What's the next invoice number for this client?",
      'How many invoices have we created?',
    ],
    invoiceNumberPadding: [
      'invoice padding',
      'number padding',
      'padding length',
      'How many digits are invoices padded to?',
      "What's the invoice number format?",
    ],
    createdAt: [
      'added',
      'created date',
      'date joined',
      'When was this client added?',
      'Show new clients from last month',
    ],
    updatedAt: [
      'modified',
      'last updated',
      'edit date',
      'When was this client last updated?',
      'Who updated the client record?',
    ],
    deletedAt: [
      'deleted',
      'archived',
      'removed',
      'Show deleted clients',
      'When was this client removed?',
    ],
  },
  Project: {
    id: ['project id', 'What is the project id?', 'Find project by id'],
    name: [
      'project',
      'project name',
      'work project',
      'assignment',
      'Show all projects called X',
      'Find project by name',
    ],
    description: [
      'summary',
      'project description',
      'overview',
      "What's the project about?",
      'Show project details',
    ],
    clientId: [
      'client id',
      'customer',
      'company',
      'What client is this project for?',
      'Show all projects for client X',
    ],
    isActive: [
      'ongoing',
      'active',
      'in progress',
      'status',
      'Which projects are active?',
      'Show finished projects',
    ],
    startDate: [
      'start date',
      'begin date',
      'launched on',
      'When did this project start?',
      'Show projects started in 2024',
    ],
    endDate: [
      'end date',
      'completion date',
      'deadline',
      'When is this project due?',
      'What is the end date for project X?',
    ],
    isBillableProject: [
      'billable',
      'invoiced',
      'billable project',
      'charged project',
      'Is this project billable?',
      'Show only billable projects',
    ],
    defaultBillable: [
      'billable by default',
      'default billing status',
      'Are tasks on this project billable by default?',
    ],
    hourlyRate: [
      'project rate',
      'hourly rate',
      'charge rate',
      "What is the project's hourly rate?",
      'Set new rate for project',
    ],
    allocatedHours: [
      'hours budget',
      'budgeted hours',
      'planned time',
      'What is the time budget for this project?',
      'How many hours allocated?',
    ],
    additionalHoursAllocated: [
      'extra hours',
      'additional time',
      'overtime allotted',
      'Add extra hours to project',
      'How many additional hours were given?',
    ],
    createdAt: [
      'created',
      'added to system',
      'When was the project created?',
      'Show recent projects',
    ],
    updatedAt: ['updated', 'last modified', 'When was the project updated?'],
    deletedAt: [
      'deleted',
      'archived',
      'removed',
      'When was this project deleted?',
      'Show archived projects',
    ],
  },
  ProjectMember: {
    id: ['membership id', 'project member id', 'What is the membership id for this user/project?'],
    projectId: [
      'project',
      'project id',
      'assignment',
      'Show all members on project X',
      'What projects is this user involved in?',
    ],
    userId: [
      'user',
      'team member',
      'user id',
      'List users for a project',
      'Who is assigned to this project?',
    ],
    isBillable: [
      'billable',
      'chargeable',
      'is this user billed?',
      'Is this member billable?',
      'List non-billable project members',
    ],
    createdAt: ['added', 'joined', 'When did this person join the project?'],
    updatedAt: ['last updated', 'modified', 'When was the project member record last updated?'],
  },
  TimeEntry: {
    id: ['entry id', 'time entry id', 'What is the id of this time entry?'],
    userId: [
      'user',
      'employee',
      'who worked',
      'user id',
      'Who made this time entry?',
      'Show entries for user X',
    ],
    projectId: [
      'project',
      'project id',
      'assignment',
      'Which project is this time entry for?',
      'List entries by project',
    ],
    description: [
      'entry description',
      'work log',
      'task narrative',
      'What work was done?',
      'Show descriptions of time entries',
    ],
    startTime: [
      'start',
      'start time',
      'clock in',
      'When did this work start?',
      'Show earliest work start time',
    ],
    endTime: [
      'end',
      'end time',
      'clock out',
      'When was this work finished?',
      'Show end times for time entries',
    ],
    duration: [
      'minutes',
      'duration',
      'total time',
      'length',
      'How long did this take?',
      'What is the duration of this entry?',
    ],
    regularHours: [
      'hours',
      'regular hours',
      'work hours',
      'How many hours were logged?',
      'Show only regular hours',
    ],
    overtimeHours: [
      'overtime',
      'extra hours',
      'overtime hours',
      'How much overtime did they work?',
      'Show overtime entries',
    ],
    weekStartDate: [
      'week',
      'week start',
      'timesheet week',
      'Which week does this entry belong to?',
      'Show time entries by week',
    ],
    isBillable: [
      'billable',
      'charged',
      'can bill?',
      'Is this time entry billable?',
      'List non-billable time entries',
    ],
    createdAt: ['added', 'log created', 'When was this entry created?'],
    updatedAt: ['last modified', 'updated', 'When was this entry last updated?'],
    deletedAt: ['deleted', 'removed', 'When was this entry deleted?'],
  },
  Task: {
    id: ['task id', 'item id', 'What is the id of this task?'],
    projectId: [
      'project id',
      'assignment id',
      'related project',
      'What project is this task for?',
      'Show all tasks for project X',
    ],
    title: ['task', 'task name', 'item title', 'What is the task title?', 'Search tasks by name'],
    description: [
      'task details',
      'notes',
      'explanation',
      "What's the description of this task?",
      'Task details',
    ],
    status: [
      'state',
      'task status',
      'progress',
      "What is the task's status?",
      'Show completed tasks',
      'Show tasks in progress',
    ],
    priority: ['priority', 'urgency', 'rank', 'What is the priority level?', 'List urgent tasks'],
    assignedToUserId: [
      'assigned to',
      'responsible',
      'assignee',
      'Who is assigned this task?',
      'Show tasks assigned to user X',
    ],
    dueDate: ['due', 'deadline', 'finish by', 'When is this task due?', 'List overdue tasks'],
    completedAt: [
      'completion',
      'done at',
      'finished on',
      'When did this task complete?',
      'Show completion dates',
    ],
    createdAt: ['created', 'task added', 'When was this task created?', 'Show recent tasks'],
    updatedAt: ['last updated', 'modified', 'When was this task last updated?'],
  },
  Conversation: {
    id: ['conversation id', 'chat id', 'What is the id of this chat?', 'Find conversation by id'],
    userId: [
      'user',
      'starter',
      'creator id',
      'Who started the conversation?',
      'Find all conversations for user X',
    ],
    title: [
      'title',
      'subject',
      'chat topic',
      "What's the chat about?",
      'Search by conversation topic',
    ],
    isActive: [
      'active',
      'open',
      'archived',
      'status',
      'Is this conversation active?',
      'Find archived conversations',
    ],
    createdAt: [
      'created',
      'opened at',
      'When did this conversation start?',
      'List new conversations',
    ],
    updatedAt: [
      'last active',
      'updated',
      'When was this chat last active?',
      'Show recently updated conversations',
    ],
  },
  Message: {
    id: ['message id', 'What is the id of this message?'],
    conversationId: [
      'chat',
      'conversation',
      'thread id',
      'Which chat is this message part of?',
      'Show all messages in conversation X',
    ],
    role: [
      'sender type',
      'author role',
      'is user or system',
      'Who sent this message?',
      'Show only assistant messages',
    ],
    content: ['message', 'text', 'body', 'What did they say?', 'Search messages by content'],
    metadata: [
      'extra info',
      'meta',
      'additional data',
      'What additional data is stored with this message?',
    ],
    createdAt: ['sent at', 'time sent', 'When was this message sent?', 'Show message timestamps'],
  },
  ResponseRating: {
    id: ['rating id', 'feedback id', 'What is the id of this rating?'],
    messageId: [
      'message id',
      'responded to',
      'What message is this rating for?',
      'Find ratings for message X',
    ],
    userId: [
      'user',
      'evaluator',
      'judge id',
      'Who submitted this rating?',
      'Show ratings given by this user',
    ],
    ratingType: [
      'type',
      'preview/report',
      'what rated',
      'Is this a preview or report rating?',
      'Show only report ratings',
    ],
    rating: [
      'score',
      'rating value',
      'grade',
      'bad/ok/good',
      'What rating was given?',
      "Show only 'bad' ratings",
    ],
    feedback: [
      'feedback',
      'user comment',
      'notes',
      'What feedback did they write?',
      'Show feedback text',
    ],
    metadata: ['extra info', 'additional notes', 'Is there extra context with this rating?'],
    createdAt: [
      'rated at',
      'when rated',
      'When did this feedback get added?',
      'Show recent ratings',
    ],
  },
  Invoice: {
    id: ['invoice id', 'bill id', 'What is the id of this invoice?', 'Find invoice by id'],
    invoiceNumber: [
      'invoice number',
      'bill number',
      'reference number',
      'What is this invoice number?',
      'Search invoices by number',
    ],
    clientId: [
      'client id',
      'customer',
      'for client',
      'Who is this invoice for?',
      'List invoices for client X',
    ],
    status: [
      'status',
      'state',
      'invoice state',
      'paid/unpaid/cancelled',
      'What is the status of this invoice?',
      'Show unpaid invoices',
      'Show overdue bills',
    ],
    paypalInvoiceId: [
      'paypal invoice',
      'paypal reference',
      'external id',
      "What's the PayPal ID for this invoice?",
    ],
    paypalInvoiceUrl: [
      'paypal url',
      'view link',
      'payment link',
      'How can I view this on PayPal?',
      'Get the invoice payment link',
    ],
    issueDate: [
      'invoice date',
      'issued on',
      'date sent',
      'When was this invoice issued?',
      'Show invoices by date',
    ],
    dueDate: [
      'due',
      'due date',
      'payment deadline',
      'When is this invoice due?',
      'List invoices due next week',
    ],
    paidDate: [
      'paid',
      'payment date',
      'settled on',
      'When was this invoice paid?',
      'Show paid invoices',
    ],
    subtotal: [
      'subtotal',
      'before tax',
      'base amount',
      "What's the subtotal?",
      'Show totals before tax',
    ],
    taxRate: ['tax', 'tax %', 'tax rate', "What's the tax rate?", 'Show tax applied to invoices'],
    taxAmount: [
      'tax amount',
      'tax total',
      'sales tax',
      'How much tax was charged?',
      'Show tax on invoice',
    ],
    discountAmount: [
      'discount',
      'discount total',
      'reduction',
      'What discount was applied to this invoice?',
      'Show all discounted invoices',
    ],
    totalAmount: [
      'total',
      'total amount',
      'invoice total',
      "What's the full invoice amount?",
      'Show invoice totals',
    ],
    amountPaid: [
      'paid amount',
      'amount paid',
      'payments made',
      'How much has been paid?',
      'Show partial payments',
    ],
    amountDue: [
      'outstanding',
      'due',
      'amount owed',
      'What amount is still due?',
      'Show invoices with balances',
    ],
    note: [
      'note',
      'internal note',
      'message to client',
      'Are there notes on this invoice?',
      'Show invoice comments',
    ],
    termsAndConditions: [
      'terms',
      'terms and conditions',
      't&c',
      'What are the invoice terms?',
      'Show payment conditions',
    ],
    createdBy: ['created by', 'author id', 'Who created this invoice?', 'Show invoices by author'],
    sentBy: ['sent by', 'sender id', 'Who sent this invoice?', 'Show invoices sent by user X'],
    sentAt: [
      'sent at',
      'date sent',
      'When was this invoice emailed?',
      'List recently sent invoices',
    ],
    createdAt: ['created', 'invoice made', 'When was this invoice made?', 'Show newest invoices'],
    updatedAt: ['modified', 'last updated', 'When was this invoice last updated?'],
  },
  InvoiceItem: {
    id: ['item id', 'line item id', 'What is this invoice item id?', 'Find item by id'],
    invoiceId: [
      'invoice id',
      'parent invoice',
      'bill id',
      'Which invoice does this item belong to?',
      'Show all items for invoice X',
    ],
    projectId: [
      'project',
      'project id',
      'related project',
      'What project is this item for?',
      'Show invoice items for project Y',
    ],
    description: [
      'item description',
      'service description',
      "What's the item description?",
      'Show descriptions of invoice items',
    ],
    quantity: ['qty', 'amount', 'number', 'How many units for this item?', 'Show item quantities'],
    unitPrice: [
      'price per unit',
      'unit price',
      'rate',
      "What's the unit price?",
      'Show price per unit',
    ],
    amount: [
      'total',
      'line amount',
      'item total',
      'What is the item total?',
      'Calculate total for line item',
    ],
    timeEntryIds: [
      'time entries',
      'linked time entries',
      'entry ids',
      'Which time entries make up this item?',
      'Show all time entry links',
    ],
    createdAt: ['added', 'created', 'When was this item added?'],
  },
  InvoicePayment: {
    id: ['payment id', 'transaction id', 'What is the id of this payment?', 'Find payment by id'],
    invoiceId: [
      'invoice',
      'invoice id',
      'bill id',
      'Which invoice was paid?',
      'Show payments for invoice X',
    ],
    paypalPaymentId: [
      'paypal transaction',
      'paypal payment id',
      'What is the PayPal reference for this payment?',
    ],
    amount: ['amount', 'payment amount', 'paid', 'How much was paid?', 'Show payment amounts'],
    paymentDate: [
      'date',
      'payment date',
      'when paid',
      'When was payment made?',
      'List payments by date',
    ],
    paymentMethod: [
      'method',
      'payment type',
      'how paid',
      'What payment method was used?',
      'List credit card payments',
    ],
    note: [
      'note',
      'payment note',
      'comment',
      'Is there a note on this payment?',
      'Show payment remarks',
    ],
    createdAt: ['recorded', 'created', 'When was this payment recorded?'],
  },
};

/**
 * Main database tables (admin access only)
 */
export const MAIN_DB_TABLES = ['Client'];

/**
 * Client database tables (user and admin access)
 */
export const CLIENT_DB_TABLES = [
  'Project',
  'ProjectMember',
  'TimeEntry',
  'Task',
  'Conversation',
  'Message',
  'ResponseRating',
  'Invoice',
  'InvoiceItem',
  'InvoicePayment',
];
